// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmowibbugogzksfyxgng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inptb3dpYmJ1Z29nemtzZnl4Z25nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDU5MjMsImV4cCI6MjA3MzUyMTkyM30.2KooQpHF4sGSsD5_PABGAYpQcqe-opwgnwyitEoX83I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});